domain_name: bettertwitter.ninja
letsencrypt_email: 24841687+usern132@users.noreply.github.com

subdomains:
  - prefix: "www"
    port: 5001
    include_root: true
  - prefix: "api"
    port: 8080
  - prefix: "grafana"
    port: 3000
