networks:
  itu-minitwit-network:
    name: itu-minitwit-network

volumes:
  prometheus_data:
  grafana-storage:

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - itu-minitwit-network
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - itu-minitwit-network

  itu-api-server:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    image: itu-api-server
    container_name: api
    ports:
      - "8080:8080"
      - "9185:9185"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - DATABASE_PATH=/app/db/chat.db
      - OTEL_PROMETHEUS_URI_PREFIX=http://*:9185/
    volumes:
      - ./src/Web/chat.db:/app/db/chat.db
    networks:
      - itu-minitwit-network

  itu-web-server:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    image: itu-web-server
    container_name: web
    ports:
      - "5001:5001"
      - "9184:9184"
    environment:
      - ASPNETCORE_URLS=http://+:5001
      - OTEL_PROMETHEUS_URI_PREFIX=http://*:9184/
    volumes:
      - ./src/Web/chat.db:/app/db/chat.db
    networks:
      - itu-minitwit-network