- name: Wait for Droplets to be accessible
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for SSH to be available
      ansible.builtin.wait_for_connection:
        delay: 1
        timeout: 300

- name: Deploy web servers
  hosts: prod, staging
  become: true
  roles:
    - role: nginx
      vars:
        nginx_template_file: "templates/web.conf.j2"
        nginx_site_name: "{{ domain_name }}.conf"
      
- name: Deploy load balancers
  hosts: loadbalancers
  become: true
  roles:
    - role: nginx
      vars:
        nginx_template_file: "templates/lb.conf.j2"
        nginx_site_name: "lb.conf"
    - role: keepalived
    - role: ufw