- name: Wait for Droplets to be accessible
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for SSH to be available
      ansible.builtin.wait_for_connection:
        delay: 1
        timeout: 300

- name: Deploy web servers
  hosts: prod, staging
  become: true
  roles:
    - role: nginx
      vars:
        nginx_template_file: "templates/web.conf.j2"
        nginx_site_name: "{{ domain_name }}.conf"
      
- name: Deploy load balancers
  hosts: loadbalancers
  become: true
  
  pre_tasks:
    - name: Gather subdomains from vars for certbot
      ansible.builtin.set_fact:
        cert_domains: "{{ cert_domains | default([]) + [item.prefix ~ '.' ~ domain_name] + ([domain_name] if item.include_root | default(false) else []) }}"
      loop: "{{ subdomains }}"

    - name: Check if Let's Encrypt certificates already exist
      ansible.builtin.stat:
        path: "/etc/letsencrypt/live/{{ cert_domains[0] }}/fullchain.pem"
      register: ssl_cert_check

  roles:
    - role: nginx
      vars:
        nginx_template_file: "templates/loadbalancers.conf.j2"
        nginx_site_name: "loadbalancers.conf"
        cert_exists: "{{ ssl_cert_check.stat.exists }}"

    - role: geerlingguy.certbot
      vars:
        certbot_admin_email: "{{ letsencrypt_email }}"
        certbot_create_if_missing: true
        certbot_create_standalone_stop_services: 
          - nginx
        certbot_certs:
          - domains: "{{ cert_domains }}"

    - role: keepalived
    - role: ufw

  post_tasks:
    - name: Re-apply Nginx role to add HTTPS configuration if certificates were just created
      ansible.builtin.include_role:
        name: nginx
      vars:
        cert_exists: true
        nginx_template_file: "templates/loadbalancers.conf.j2"
        nginx_site_name: "loadbalancers.conf"
      when: not ssl_cert_check.stat.exists
    - name: Test secure connection to SSL domain
      uri:
        url: "https://{{ domain_name }}/" 
        status_code: 200
      delegate_to: localhost