- name: Wait for Droplets to be accessible
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for SSH to be available
      ansible.builtin.wait_for_connection:
        delay: 1
        timeout: 300

- name: Deploy web servers
  hosts: prod, staging
  become: true
  roles:
    - role: nginx
      vars:
        nginx_template_file: "templates/web.conf.j2"
        nginx_site_name: "{{ domain_name }}.conf"
      
- name: Deploy load balancers
  hosts: loadbalancers
  become: true
  
  pre_tasks:
    - name: Gather subdomains from vars for certbot
      ansible.builtin.set_fact:
        cert_domains: "{{ cert_domains | default([]) + [item.prefix ~ '.' ~ domain_name] + ([domain_name] if item.include_root | default(false) else []) }}"
      loop: "{{ subdomains }}"

    - name: Check if Let's Encrypt certificates already exist
      ansible.builtin.stat:
        path: "/etc/letsencrypt/live/{{ cert_domains[0] }}/fullchain.pem"
      register: ssl_cert_check

    - name: Wait for DNS propagation for all domains (if DNS A records were created shortly before running this playbook)
      ansible.builtin.command: "dig +short {{ item }}"
      register: dns_check
      until: "reserved_ip in dns_check.stdout"
      retries: 200
      delay: 5
      delegate_to: localhost
      become: false
      changed_when: false
      loop: "{{ cert_domains }}"

  roles:
    - role: nginx
      vars:
        nginx_template_file: "templates/loadbalancers.conf.j2"
        nginx_site_name: "loadbalancers.conf"
        cert_exists: "{{ ssl_cert_check.stat.exists }}"

    - role: geerlingguy.certbot
      vars:
        certbot_admin_email: "{{ letsencrypt_email }}"
        certbot_create_if_missing: true
        certbot_create_standalone_stop_services: 
          - nginx
        certbot_certs:
          - domains: "{{ cert_domains }}"
      # The certificate is only obtained once: in the primary load balancer.
      # It then gets copied to the backup load balancers.
      when: inventory_hostname == groups['loadbalancers'][0]

    - role: keepalived
    - role: ufw

  post_tasks:
    - name: Archive Let's Encrypt directory on primary load balancer
      ansible.builtin.command: tar -czf /tmp/letsencrypt.tar.gz -C /etc letsencrypt
      when: inventory_hostname == groups['loadbalancers'][0]

    - name: Fetch Let's Encrypt archive to local runner
      ansible.builtin.fetch:
        src: /tmp/letsencrypt.tar.gz
        dest: /tmp/letsencrypt.tar.gz
        flat: true
      when: inventory_hostname == groups['loadbalancers'][0]

    - name: Copy Let's Encrypt archive to backup load balancers
      ansible.builtin.copy:
        src: /tmp/letsencrypt.tar.gz
        dest: /tmp/letsencrypt.tar.gz
      when: inventory_hostname != groups['loadbalancers'][0]

    - name: Extract Let's Encrypt archive on backup load balancers
      ansible.builtin.command: tar -xzf /tmp/letsencrypt.tar.gz -C /etc
      when: inventory_hostname != groups['loadbalancers'][0]

    - name: Re-apply Nginx role to add HTTPS configuration if certificates were just created
      ansible.builtin.include_role:
        name: nginx
      vars:
        cert_exists: true
        nginx_template_file: "templates/loadbalancers.conf.j2"
        nginx_site_name: "loadbalancers.conf"
      when: not ssl_cert_check.stat.exists

    - ansible.builtin.meta: flush_handlers

    - name: Restart Nginx to apply certificates
      ansible.builtin.service:
        name: nginx
        state: restarted
      when: not ssl_cert_check.stat.exists

    - name: Test secure connection to SSL domain
      uri:
        url: "https://{{ domain_name }}/" 
        status_code: 200
      delegate_to: localhost
      retries: 5
      delay: 3
      become: false