/*
 * Minitwit API
 *
 * Minitwit API
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.IO;
using System.Reflection;
using DotNetEnv;
using Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.OpenApi.Models;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Serialization;
using Org.OpenAPITools.Authentication;
using Org.OpenAPITools.Filters;
using Org.OpenAPITools.Formatters;
using Org.OpenAPITools.OpenApi;

namespace Org.OpenAPITools
{
    /// <summary>
    /// Startup
    /// </summary>
    public class Startup
    {
        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="configuration"></param>
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        /// <summary>
        /// The application configuration.
        /// </summary>
        public IConfiguration Configuration { get; }

        /// <summary>
        /// This method gets called by the runtime. Use this method to add services to the container.
        /// </summary>
        /// <param name="services"></param>
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services
                // Don't need the full MVC stack for an API, see https://andrewlock.net/comparing-startup-between-the-asp-net-core-3-templates/
                .AddControllers(options =>
                {
                    options.InputFormatters.Insert(0, new InputFormatterStream());
                })
                .AddNewtonsoftJson(opts =>
                {
                    opts.SerializerSettings.ContractResolver =
                        new CamelCasePropertyNamesContractResolver();
                    opts.SerializerSettings.Converters.Add(
                        new StringEnumConverter { NamingStrategy = new CamelCaseNamingStrategy() }
                    );
                });
            services.AddHealthChecks().AddCheck<DatabaseHealthCheck>("database");
            services.AddSwaggerGen(c =>
            {
                c.EnableAnnotations(
                    enableAnnotationsForInheritance: true,
                    enableAnnotationsForPolymorphism: true
                );

                c.SwaggerDoc(
                    "1.0",
                    new OpenApiInfo
                    {
                        Title = "Minitwit API",
                        Description = "Minitwit API (ASP.NET Core 8.0)",
                        TermsOfService = new Uri(
                            "https://github.com/openapitools/openapi-generator"
                        ),
                        Contact = new OpenApiContact
                        {
                            Name = "OpenAPI-Generator Contributors",
                            Url = new Uri("https://github.com/openapitools/openapi-generator"),
                            Email = "",
                        },
                        License = new OpenApiLicense
                        {
                            Name = "NoLicense",
                            Url = new Uri("http://localhost"),
                        },
                        Version = "1.0",
                    }
                );
                c.CustomSchemaIds(type => type.FriendlyId(true));
                c.IncludeXmlComments(
                    $"{AppContext.BaseDirectory}{Path.DirectorySeparatorChar}{Assembly.GetExecutingAssembly().GetName().Name}.xml"
                );

                // Include DataAnnotation attributes on Controller Action parameters as OpenAPI validation rules (e.g required, pattern, ..)
                // Use [ValidateModelState] on Actions to actually validate it in C# as well!
                c.OperationFilter<GeneratePathParamsValidationFilter>();
            });

            Env.Load("../../.env");
            var rawConnectionString = Environment.GetEnvironmentVariable("DB_URL");
            if (string.IsNullOrWhiteSpace(rawConnectionString))
            {
                throw new InvalidOperationException("Environment variable 'DB_URL' is not set");
            }

            var connectionString = NormalizeNpgsqlConnectionString(rawConnectionString);
            services.AddSwaggerGenNewtonsoftSupport();
            services.AddDbContext<ChatDbContext>(options => options.UseNpgsql(connectionString));
        }

        /// <summary>
        /// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        /// </summary>
        /// <param name="app"></param>
        /// <param name="env"></param>
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseDefaultFiles();
            app.UseStaticFiles();
            app.UseSwagger(c =>
                {
                    c.RouteTemplate = "openapi/{documentName}/openapi.json";
                })
                .UseSwaggerUI(c =>
                {
                    // set route prefix to openapi, e.g. http://localhost:8080/openapi/index.html
                    c.RoutePrefix = "openapi";
                    //TODO: Either use the SwaggerGen generated OpenAPI contract (generated from C# classes)
                    c.SwaggerEndpoint("/openapi/1.0/openapi.json", "Minitwit API");

                    //TODO: Or alternatively use the original OpenAPI contract that's included in the static files
                    // c.SwaggerEndpoint("/openapi-original.json", "Minitwit API Original");
                });
            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapHealthChecks("/health");
                endpoints.MapHealthChecks(
                    "/health/live",
                    new Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckOptions
                    {
                        Predicate = _ => false,
                    }
                );
                endpoints.MapControllers();
            });
        }

        private static string NormalizeNpgsqlConnectionString(string connectionString)
        {
            if (
                Uri.TryCreate(connectionString, UriKind.Absolute, out var uri)
                && (uri.Scheme == "postgres" || uri.Scheme == "postgresql")
            )
            {
                return ToNpgsqlConnectionString(uri);
            }

            return connectionString;
        }

        private static string ToNpgsqlConnectionString(Uri uri)
        {
            var userInfo = uri.UserInfo.Split(':', 2);
            var db = uri.AbsolutePath.TrimStart('/');
            var query = System.Web.HttpUtility.ParseQueryString(uri.Query);
            var sslMode = query["sslmode"] ?? "Require";

            return $"Host={uri.Host};Port={uri.Port};Database={db};Username={Uri.UnescapeDataString(userInfo[0])};Password={Uri.UnescapeDataString(userInfo[1])};SSL Mode={sslMode};Trust Server Certificate=true;";
        }
    }
}
