/*
 * Minitwit API
 *
 * Minitwit API
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.Metrics;
using System.Linq.Expressions;
using System.Text.Json;
using System.Threading.Tasks;
using Core.Model;
using Infrastructure;
using Infrastructure.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Org.OpenAPITools.Attributes;
using Org.OpenAPITools.Models;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace Org.OpenAPITools.Controllers
{
    /// <summary>
    ///
    /// </summary>
    [ApiController]
    public class MinitwitApiController(ChatDbContext dbContext) : ControllerBase
    {
        private readonly CheepRepository _cheepRepository = new CheepRepository(dbContext);
        private readonly AuthorRepository _authorRepository = new AuthorRepository(dbContext);

        private LatestValue late = new LatestValue();

        public Singleton single = Singleton.Instance;

        /// <summary>
        ///
        /// </summary>
        /// <remarks>Get list of users followed by the given user.  - Query param &#x60;?no&#x3D;&#x60; limits result count. - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="username"></param>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <param name="no">Optional: &#x60;no&#x60; limits result count</param>
        /// <response code="200">Success</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        /// <response code="404">User not found (no response body)</response>
        [HttpGet]
        [Route("/fllws/{username}")]
        [ValidateModelState]
        [SwaggerOperation("GetFollow")]
        [SwaggerResponse(statusCode: 204, type: typeof(FollowsResponse), description: "Success")]
        [SwaggerResponse(
            statusCode: 403,
            type: typeof(ErrorResponse),
            description: "Unauthorized - Must include correct Authorization header"
        )]
        public virtual async Task<IActionResult> GetFollow(
            [FromRoute(Name = "username")] [Required] string username,
            [FromHeader(Name = "Authorization")] [Required()] string authorization,
            [FromQuery(Name = "latest")] int? latest,
            [FromQuery(Name = "no")] int? no
        )
        {
            if (!authorization.Equals("Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh"))
            {
                string error =
                    "{\n  \"error_msg\" : \"You are not authorized to use this resource!\",\n  \"status\" : 403\n}";
                var example =
                    error != null ? JsonConvert.DeserializeObject<ErrorResponse>(error) : default;
                single.latest = (int)latest;
                Console.WriteLine("error here: 1");

                single.IncrementGetFollowersCounter((int)example.Status);
                return new ObjectResult(example);
            }

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403, default);
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            Author author = await _authorRepository.ReturnBasedOnNameAsync(username);

            List<int> ids = author.Follows;

            List<Author> authors = await _authorRepository.GetAuthorsFromIdList(ids);

            List<string> names = new List<string>();

            for (int i = 0; i < authors.Count; i++)
            {
                names.Add(authors[i].Name);
            }

            string exampleJson = null;
            var obj = new { follows = names };

            exampleJson = JsonConvert.SerializeObject(obj, Formatting.Indented);
            //exampleJson = "{\n  \"error_msg\" : \"You are not authorized to use this resource!\",\n  \"status\" : 403\n}";

            single.latest = (int)latest;
            Console.WriteLine("helpp");
            Console.WriteLine(exampleJson);

            single.IncrementGetFollowersCounter(
                JsonConvert.DeserializeObject<ErrorResponse>(exampleJson)?.Status ?? 200
            );
            return new ObjectResult(exampleJson);
        }

        /// <summary>
        ///
        /// </summary>
        /// <remarks>Returns the latest ID saved</remarks>
        /// <response code="200">Success</response>
        /// <response code="500">Internal Server Error</response>
        [HttpGet]
        [Route("/latest")]
        [ValidateModelState]
        [SwaggerOperation("GetLatestValue")]
        [SwaggerResponse(statusCode: 200, type: typeof(LatestValue), description: "Success")]
        [SwaggerResponse(
            statusCode: 500,
            type: typeof(ErrorResponse),
            description: "Internal Server Error"
        )]
        public virtual IActionResult GetLatestValue()
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default);

            string exampleJson = null;
            exampleJson = $"{{\n  \"latest\" : {single.latest}\n}}";
            //saved for if we have to make a error message
            //exampleJson = "{\n  \"error_msg\" : \"You are not authorized to use this resource!\",\n  \"status\" : 403\n}";
            var example =
                exampleJson != null
                    ? JsonConvert.DeserializeObject<LatestValue>(exampleJson)
                    : default;
            //TODO: Change the data returned
            ObjectResult result = new ObjectResult(example);
            single.IncrementLatestCounter(result.StatusCode ?? 200);
            return result;
        }

        /// <summary>
        ///
        /// </summary>
        /// <remarks>Get recent messages.  - Filters out flagged messages - Returns a list of recent messages (max defined by &#x60;?no&#x3D;&#x60; param) - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <param name="no">Optional: &#x60;no&#x60; limits result count</param>
        /// <response code="200">Success</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        [HttpGet]
        [Route("/msgs")]
        [ValidateModelState]
        [SwaggerOperation("GetMessages")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Message>), description: "Success")]
        [SwaggerResponse(
            statusCode: 403,
            type: typeof(ErrorResponse),
            description: "Unauthorized - Must include correct Authorization header"
        )]
        public virtual async Task<IActionResult> GetMessages(
            [FromHeader(Name = "Authorization")] [Required()] string authorization,
            [FromQuery(Name = "latest")] int? latest,
            [FromQuery(Name = "no")] int? no
        )
        {
            if (!authorization.Equals("Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh"))
            {
                string error =
                    "{\n  \"error_msg\" : \"You are not authorized to use this resource!\",\n  \"status\" : 403\n}";
                var nuhuh =
                    error != null ? JsonConvert.DeserializeObject<ErrorResponse>(error) : default;
                single.latest = (int)latest;
                Console.WriteLine("error here: 2");
                single.IncrementGetMessagesCounter((int)nuhuh.Status);
                return new ObjectResult(nuhuh);
            }

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403, default);
            string exampleJson = null;
            var cheeps = await _cheepRepository.ReadCheeps();

            var cheep = cheeps[0];

            exampleJson =
                $@"[
            {{
            ""pub_date"" : ""{cheep.TimeStamp}"",
            ""user"" : ""{cheep.Author.Name}"",
            ""content"" : ""{cheep.Text}""
            }},
            {{
            ""pub_date"" : ""{cheep.TimeStamp}"",
            ""user"" : ""{cheep.Author.Name}"",
            ""content"" : ""{cheep.Text}""
            }}
            ]";
            var example =
                exampleJson != null
                    ? JsonConvert.DeserializeObject<List<Message>>(exampleJson)
                    : default;
            single.latest = (int)latest;
            var result = new ObjectResult(example);
            single.IncrementGetMessagesCounter(result.StatusCode ?? 200);
            return result;
        }

        /// <summary>
        ///
        /// </summary>
        /// <remarks>Get messages for a specific user.  - Returns messages authored by the specified user - Filtered by unflagged - Returns a list of recent messages for the user (max defined by &#x60;?no&#x3D;&#x60; param) - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="username"></param>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <param name="no">Optional: &#x60;no&#x60; limits result count</param>
        /// <response code="200">Success</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        /// <response code="404">User not found (no response body)</response>
        [HttpGet]
        [Route("/msgs/{username}")]
        [ValidateModelState]
        [SwaggerOperation("GetMessagesPerUser")]
        [SwaggerResponse(statusCode: 204, type: typeof(List<Message>), description: "Success")]
        [SwaggerResponse(
            statusCode: 403,
            type: typeof(ErrorResponse),
            description: "Unauthorized - Must include correct Authorization header"
        )]
        public virtual async Task<IActionResult> GetMessagesPerUser(
            [FromRoute(Name = "username")] [Required] string username,
            [FromHeader(Name = "Authorization")] [Required()] string authorization,
            [FromQuery(Name = "latest")] int? latest,
            [FromQuery(Name = "no")] int? no
        )
        {
            if (!authorization.Equals("Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh"))
            {
                string error =
                    "{\n  \"error_msg\" : \"You are not authorized to use this resource!\",\n  \"status\" : 403\n}";
                var nuhuh =
                    error != null ? JsonConvert.DeserializeObject<ErrorResponse>(error) : default;
                single.latest = (int)latest;
                Console.WriteLine("error here: 3");
                single.IncrementGetMessagesPerUserCounter((int)nuhuh.Status);
                return new ObjectResult(nuhuh);
            }

            string exampleJson = null;
            Author author = await _authorRepository.ReturnBasedOnNameAsync(username);

            var cheeps = await _cheepRepository.GetAuthorCheeps(author.AuthorId);

            var cheep = cheeps[0];

            exampleJson =
                $@"[
            {{
            ""pub_date"" : ""{cheep.TimeStamp}"",
            ""user"" : ""{cheep.Author.Name}"",
            ""content"" : ""{cheep.Text}""
            }},
            {{
            ""pub_date"" : ""{cheep.TimeStamp}"",
            ""user"" : ""{cheep.Author.Name}"",
            ""content"" : ""{cheep.Text}""
            }}
            ]";
            var example =
                exampleJson != null
                    ? JsonConvert.DeserializeObject<List<Message>>(exampleJson)
                    : default;
            single.latest = (int)latest;
            var result = new ObjectResult(example);
            single.IncrementGetMessagesPerUserCounter(result.StatusCode ?? 200);
            return result;
        }

        /// <summary>
        ///
        /// </summary>
        /// <remarks>Follow or unfollow a user on behalf of &#x60;username&#x60;.  - Body must contain either &#x60;follow: &lt;user&gt;&#x60; or &#x60;unfollow: &lt;user&gt;&#x60;</remarks>
        /// <param name="username"></param>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="payload"></param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <response code="204">No Content</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        /// <response code="404">User not found (no response body)</response>
        [HttpPost]
        [Route("/fllws/{username}")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("PostFollow")]
        [SwaggerResponse(
            statusCode: 403,
            type: typeof(ErrorResponse),
            description: "Unauthorized - Must include correct Authorization header"
        )]
        public virtual async Task<IActionResult> PostFollow(
            [FromRoute(Name = "username")] [Required] string username,
            [FromHeader(Name = "Authorization")] [Required()] string authorization,
            [FromBody] FollowAction payload,
            [FromQuery(Name = "latest")] int? latest
        )
        {
            if (!authorization.Equals("Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh"))
            {
                string error =
                    "{\n  \"error_msg\" : \"You are not authorized to use this resource!\",\n  \"status\" : 403\n}";
                var example =
                    error != null ? JsonConvert.DeserializeObject<ErrorResponse>(error) : default;
                single.latest = (int)latest;
                Console.WriteLine("error here: 4");
                var result = new ObjectResult(example);
                single.IncrementPostFollowersCounter(result.StatusCode ?? 200);
                return result;
            }
            Author follower = await _authorRepository.ReturnBasedOnNameAsync(username);
            if (follower == null)
            {
                return NotFound();
            }

            if (payload.Follow != null)
            {
                Author famous = await _authorRepository.ReturnBasedOnNameAsync(payload.Follow);
                if (famous == null)
                {
                    return NotFound();
                }
                _authorRepository.AddFollowerId(follower, famous.AuthorId);
            }
            else if (payload.Unfollow != null)
            {
                Author famous = await _authorRepository.ReturnBasedOnNameAsync(payload.Unfollow);
                if (famous == null)
                {
                    return NotFound();
                }
                _authorRepository.RemoveFollowerId(follower, famous.AuthorId);
            }
            else
            {
                return BadRequest(
                    new
                    {
                        status = 400,
                        error_msg = "Request must contain either 'follow' or 'unfollow'",
                    }
                );
            }

            Console.WriteLine(username);
            Console.WriteLine(payload.Follow);
            Console.WriteLine(payload.Unfollow);
            Console.WriteLine("Next round");

            single.latest = (int)latest;

            var statusCode = 204;
            single.IncrementPostFollowersCounter(statusCode);
            return StatusCode(statusCode);
        }

        /// <summary>
        ///
        /// </summary>
        /// <remarks>Post a new message as a specific user.  - Message must include &#x60;content&#x60; in the body - Stored with timestamp and &#x60;flagged&#x3D;0&#x60; - Returns empty body on success - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="username"></param>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="payload"></param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <response code="204">No Content</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        [HttpPost]
        [Route("/msgs/{username}")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("PostMessagesPerUser")]
        [SwaggerResponse(
            statusCode: 403,
            type: typeof(ErrorResponse),
            description: "Unauthorized - Must include correct Authorization header"
        )]
        public virtual async Task<IActionResult> PostMessagesPerUser(
            [FromRoute(Name = "username")] [Required] string username,
            [FromHeader(Name = "Authorization")] [Required()] string authorization,
            [FromBody] PostMessage payload,
            [FromQuery(Name = "latest")] int? latest
        )
        {
            if (!authorization.Equals("Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh"))
            {
                string error =
                    "{\n  \"error_msg\" : \"You are not authorized to use this resource!\",\n  \"status\" : 403\n}";
                var example =
                    error != null ? JsonConvert.DeserializeObject<ErrorResponse>(error) : default;
                single.latest = (int)latest;
                Console.WriteLine("error here: 5");
                single.IncrementPostMessagesPerUserCounter((int)example.Status);
                return new ObjectResult(example);
            }

            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);
            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403, default);
            var author = await _authorRepository.ReturnBasedOnNameAsync(username);
            if (author == null)
                return StatusCode(404);

            await _cheepRepository.CreateCheep(author, payload.Content);
            single.latest = (int)latest;

            var statusCode = 204;
            single.IncrementPostMessagesPerUserCounter(statusCode);
            return StatusCode(statusCode);
        }

        /// <summary>
        ///
        /// </summary>
        /// <remarks>Register a new user. - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="payload"></param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <response code="204">No Content</response>
        /// <response code="400">Bad Request | Possible reasons:  - missing username  - invalid email  - password missing  - username already taken</response>
        [HttpPost]
        [Route("/register")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("PostRegister")]
        [SwaggerResponse(
            statusCode: 400,
            type: typeof(ErrorResponse),
            description: "Bad Request | Possible reasons:  - missing username  - invalid email  - password missing  - username already taken"
        )]
        public virtual async Task<IActionResult> PostRegister(
            [FromBody] RegisterRequest payload,
            [FromQuery(Name = "latest")] int? latest
        )
        {
            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default);

            _authorRepository.CreateAuthor(payload.Username, payload.Email);

            single.latest = (int)latest;

            var statusCode = 204;
            single.IncrementPostRegisterCounter(statusCode);
            return StatusCode(204);
        }
    }
}
