name: Smoke Deploy

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

concurrency:
  group: staging-deploy
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/Deploy.yml
    with:
      image_tag: staging
      environment: Staging
    secrets: inherit
